trigger: none
#  branches:
#    include:
#      - main
#  paths:
#    include:
#      - .ado/*
#      - .azure/*

pool:
  name: 'Minecraft server'
  vmImage: 'ubuntu-latest'

variables:
  - group: 'Production Variables'

pr: none

steps:
  - task: AzureCLI@2
    displayName: Create or update the resource group
    inputs:
      azureSubscription: '$(azureServiceConnectionName)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az group create --location $(location) --name $(resourceGroupName)

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Deploy all infrastructure'
    inputs:
      connectedServiceName: $(azureServiceConnectionName)
      location: $(location)
      resourceGroupName: $(resourceGroupName)
      csmFile: .azure/bicep/infrastructure.bicep
      overrideParameters: 
        -appName $(appName)
        -env $(environment)
      deploymentOutputs: infrastructureAsCodeOutputs

  - powershell: |
      Write-Host "Value of infrastructureAsCodeOutputs is: $(infrastructureAsCodeOutputs)"

      # Convert JSON-like string to a PowerShell object
      $object = ConvertFrom-Json '$(infrastructureAsCodeOutputs)'

      # Access specific properties
      $cosmosDBKey = $object.cosmosDBKey.value
      $cosmosDBContainerName = $object.cosmosDBContainerName.value
      $cosmosDBDatabaseName = $object.cosmosDBDatabaseName.value
      $cosmosDBEndpoint = $object.cosmosDBEndpoint.value
      $cosmosDBLocation = $object.cosmosDBLocation.value

      # Output the values to verify
      Write-Host "Cosmos DB Key: $cosmosDBKey"
      Write-Host "Cosmos DB Container Name: $cosmosDBContainerName"
      Write-Host "Cosmos DB Database Name: $cosmosDBDatabaseName"
      Write-Host "Cosmos DB Endpoint: $cosmosDBEndpoint"
      Write-Host "Cosmos DB Location: $cosmosDBLocation"

      # $cosmosDBEndpoint=$var.cosmosDBEndpoint.value

      # echo "##vso[task.setvariable variable=cosmosDBEndpoint]$cosmosDBEndpoint"
      # Write-Host "Value of cosmosDBEndpoint is: $cosmosDBEndpoint"



